project_id = "dmmzlxeetlcsvyiaauna"

[functions.analyze-file]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

[functions.doc-chat]
verify_jwt = false

[functions.categorize-files]
verify_jwt = false

[functions.deep-categorize]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp-otp]
verify_jwt = false

[functions.get-shared-file]
verify_jwt = false

[functions.support-chat]
verify_jwt = false
