project_id = "dmmzlxeetlcsvyiaauna"

[functions.analyze-file]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

[functions.doc-chat]
verify_jwt = false

[functions.categorize-files]
verify_jwt = false
